# Generated by Django 5.2.9 on 2026-01-18 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('ML', 'Masala Chai'), ('GR', 'Ginger Chai'), ('CC', 'Cardamom Chai'), ('TC', 'Tulsi Chai'), ('ElaiC', 'Elaichi Chai')], default='ML', max_length=5)),
            ],
        ),
    ]
